import { RedPacketRainConfig, PerformanceStats, RedPacketEventCallback, AnimationStateCallback, PerformanceCallback, ParticleConfig } from "./types";
export declare class RedPacketRainEngine {
    private canvas;
    private ctx;
    private config;
    private redPackets;
    private animationId;
    private isRunning;
    private isPaused;
    private lastFrameTime;
    private frameCount;
    private lastFpsTime;
    private currentFPS;
    private lastSpawnTime;
    private actualWidth;
    private actualHeight;
    private redPacketPool;
    private poolSize;
    private redPacketDataIndex;
    private onRedPacketClickCallback?;
    private onAnimationStateChangeCallback?;
    private onPerformanceUpdateCallback?;
    private stats;
    private redPacketImage;
    private lastClickTime;
    private clickDebounceDelay;
    private debugClicks;
    private particles;
    private particlePool;
    private particlePoolSize;
    private particleConfig;
    constructor(canvas: HTMLCanvasElement, config?: Partial<RedPacketRainConfig>);
    private initializePool;
    private initializeParticlePool;
    private createParticle;
    private getParticleFromPool;
    private returnParticleToPool;
    private resetParticle;
    private getRedPacketFromPool;
    private returnRedPacketToPool;
    private getRedPacketData;
    private isSpecialRedPacket;
    private createRedPacket;
    private resetRedPacket;
    private optimizeConfig;
    private isUsingArrayMode;
    private loadRedPacketImage;
    private resizeCanvas;
    private bindEvents;
    private handleClick;
    private handleTouch;
    private getCanvasCoordinates;
    private handleResize;
    private checkCollision;
    private isPointInRedPacket;
    private collectRedPacket;
    private createRedPacketParticles;
    private updateParticles;
    private renderParticles;
    private spawnRedPacket;
    private updateRedPackets;
    private renderRedPackets;
    private renderRedPacket;
    private drawDefaultRedPacket;
    private animate;
    private updateFPS;
    private renderDebugInfo;
    private triggerCallbacks;
    start(): void;
    stop(): void;
    pause(): void;
    resume(): void;
    clear(): void;
    updateConfig(newConfig: Partial<RedPacketRainConfig>): void;
    getStats(): PerformanceStats;
    getCollectionStats(): {
        totalCollected: number;
        totalValue: number;
    };
    setPerformanceMode(enabled: boolean): void;
    getPerformanceMode(): boolean;
    onRedPacketClick(callback: RedPacketEventCallback): void;
    onAnimationStateChange(callback: AnimationStateCallback): void;
    onPerformanceUpdate(callback: PerformanceCallback): void;
    setParticleConfig(config: Partial<ParticleConfig>): void;
    getParticleConfig(): ParticleConfig;
    destroy(): void;
}
